version: '3.4'

services:
  db:
    image: postgres:14-bullseye
    container_name: peopleregister-db
    environment:
      POSTGRES_USER: "peopleregister"
      POSTGRES_PASSWORD: "peopleregister"
      POSTGRES_DB: "peopleregister"
    ports:
      - 5432:5432
    volumes:
      - peopleregister_db:/var/lib/postgresql/data/

volumes:
  peopleregister_db:
    name: peopleregister_db
