# Generated by Django 5.0.7 on 2024-07-25 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('birthdate', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('gender', models.CharField(max_length=12, verbose_name='Altura')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
