# Generated by Django 5.0.7 on 2024-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informar')], default='N', max_length=12, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso'),
        ),
    ]
